### ISSUE TITLE
Fix usability issues with home page

### ISSUE THREAD

**Issue by Exanite** [UF-GDA/Feedback#70]
**Todo**
- [x] Fix antipattern usage of useEffect when calculating derived data from props
- [x] Focus styling on explore and projects links
- [x] Focus styling on project squares
- [X] ~~Links should not point to 404~~ (not relevant anymore)
- [x] Project squares should have accessible descriptions
- [x] Project squares should use img tags instead of CSS backgrounds
- [x] https://github.com/DevLUp-Inc/Feedback/issues/61
- [X] https://github.com/DevLUp-Inc/Feedback/issues/65
- [x] https://github.com/DevLUp-Inc/Feedback/issues/67
- [X] https://github.com/DevLUp-Inc/Feedback/issues/79
- [x] https://github.com/DevLUp-Inc/Feedback/issues/82

**Addition comments**
For the project squares, since it involves a link and also the image, we can describe the square in a few ways:
1. "Link to project update page"
2. "Image of project update by user"
3. Use content from project update as description

**Alternative Solution**
Instead of linking to a standalone project update page, the project squares can open a modal instead.
This should be more consistent with the implementation I plan to use on the project pages.

**Note**
Since not all of these are immediately fixable, we can remove the high priority label when the ones that we can fix are fixed.
